### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MoonWalkeer** [merdw/iOS-Instagram-SSL-Pinning-Bypass#1]
![issue](https://user-images.githubusercontent.com/79293504/228134939-b9beba36-c2d8-4aad-a14a-0fdd1a7f7020.JPG)
I tried to install with different methods but unfortunately nothing worked. I hope you can help me as soon as possible.

Thanks and appreciate your efforts!

**Comment by merdw** [comment]
Firstly if you can use trollstore use it.

I didn't try with sideloadly but I changed the bundle id, name etc. so it wouldn't replace the original instagram.

I think thats the problem I will fix it in new version but for now you can change bundle id, name etc. to original Instagram and try again install.

**Comment by MoonWalkeer** [comment]
> Firstly if you can use trollstore use it.
> 
> I didn't try with sideloadly but I changed the bundle id, name etc. so it wouldn't replace the original instagram.
> 
> I think thats the problem I will fix it in new version but for now you can change bundle id, name etc. to original Instagram and try again install.

Hi there,

Thanks for your response! I am sorry for bothering you but how do I change the bundle name and id etc. sorry again for any inconvenience if you have an instagram account please reach me out
Instagram: @moonwalker7879

thanks again!

**Comment by merdw** [comment]
Updated to new version try to install original version.
